version: '3.7'

services:
  bottle:
    build: .
    image: mybottle
    container_name: mybottle
    command: >
      bash -c 'python -u main.py'
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8412:8412
  db:
    image: mysql
    container_name: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: passwd20220421
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpasswd20220421
      TZ: Asia/Tokyo
    volumes:
      - ./:/docker-entrypoint-initdb.d/

